- name: EDA Trigger Job 1
  hosts: "{{ host_group | default(all) }}"
  serial: "{{ node_count | default(1)}}"
  gather_facts: false
  tasks:
  - name: Do somthing
    debug:
      msg: "This is Job 1"

